[package]
name = "open-gdm-server"
version = "1.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
bytebuffer = "2.1.1"
chrono = "0.4.26"
colored = "2.0.4"
log = "0.4.20"
reqwest = "0.11.18"
rocket = { version = "0.5.0-rc.3" }
tokio = { version = "1.31.0", features = ["full"] }
